{
 "title": "Dice Roller Grafana Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Heatmap of Check Results",
   "type": "heatmap",
   "description": "How often a given result occurred on the die roll",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dice_rolls_total", "legendFormat": "{{roll_value}}" }
   ]
  },
  {
   "title": "Roll Counts by Result",
   "type": "timeseries",
   "description": "For each possible roll result, how often that has occurred in history",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(roll_value) (dice_rolls_total)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Roll Success Rate",
   "type": "gauge",
   "description": "How often the player's roll was likely enough to defeat the check, defined as exceeding 15.",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dice_roll_success_gauge_ratio", "legendFormat": "Success Rate" }
   ]
  },
  {
   "title": "Crit Rate",
   "type": "stat",
   "description": "How often the players roll a critical success (one of the dice rolls is a 20)",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Total Dice Rolls",
   "type": "stat",
   "description": "How many times d20 checks have happened in the lifetime of the app",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dice_rolls_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success Rate Too High",
   "type": "alertlist",
   "description": "Whether the players seem to be succeeding on their checks too often",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 18 }
  }
 ]
}