# will be copied to /tmp/otel-collector-config.yaml
# and mounted to docker container from there
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp/tempo:
    endpoint: "http://localhost:4317"
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/tempo]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]